### ISSUE TITLE
Instagram APIs

### ISSUE THREAD

**Issue by mitchdriesenga** [mitchdriesenga/Noted#5]
- Find uses of the instagram api tools for sharing the found random generated artist to a users instagram
- see if there is a way to redirect somone who views this instagram to our site to use it for themselves
- need exact api uses that can fulfil these tasks

**Comment by mbutlertechtraining** [comment]
Worked with the TA's waiting to get approval for API website where the API code information and token is stored (Events API)
https://artists.bandsintown.com/support/api-installation

**Comment by mbutlertechtraining** [comment]
We were able to pivot away from using an Instagram API and instead used an API for Genius, to display music lyrics, using Rapid API.
